version: "3"

services:  
  sql-server: # https://hub.docker.com/_/microsoft-mssql-server
    image: "mcr.microsoft.com/mssql/server:${MSSQL_SERVER_VERSION:?err}"
    environment:
        SA_PASSWORD: "${SA_PASSWORD}"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
        MSSQL_TCP_PORT: 1433
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s

  octopus-server:
    image: docker.packages.octopushq.com/octopusdeploy/octopusdeploy:${OCTOPUS_VERSION}
    environment:
      ADMIN_USERNAME: "${OCTOPUS_ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${OCTOPUS_ADMIN_PASSWORD}"
      DB_CONNECTION_STRING: "Server=db,1433;Initial Catalog=Octopus;Persist Security Info=False;User ID=sa;Password=${SA_PASSWORD};MultipleActiveResultSets=False;Connection Timeout=30;"
      SKIP_IMPORT_VERSION_CHECK: "${OCTOPUS_SKIP_IMPORT_VERSION_CHECK}"
      IMPORT_PASSWORD: "${OCTOPUS_IMPORT_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
     - "8080"
     - "10943"
    depends_on:
      - db
    stdin_open: true #Process sits and waits for ReadLine
    volumes:
      - "./docker/Volumes/octopus-server/Import:C:/Import"
      - "./docker/Volumes/octopus-server/Repository:C:/Repository"
      - "./docker/Volumes/octopus-server/MasterKey:C:/MasterKey"
    restart: always

  listening-tentacle:
    image: docker.packages.octopushq.com/octopusdeploy/tentacle:${TENTACLE_VERSION}
    depends_on:
      - octopus-server
    environment:
      ServerUsername: "${OCTOPUS_ADMIN_USERNAME}"
      ServerPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      TargetEnvironment: "Development"
      TargetRole: "app-server"
      ServerUrl: "http://octopus-server:8080"
    stdin_open: true #Process sits and waits for ReadLine
    volumes:
      - "./docker/Volumes/listening-tentacle/Applications:C:/Applications"
      - "./docker/Volumes/listening-tentacle/TentacleHome:C:/TentacleHome"
    restart: always

  polling-tentacle:
    image: docker.packages.octopushq.com/octopusdeploy/tentacle:${TENTACLE_VERSION}
    depends_on:
      - octopus-server
    environment:
      ServerUsername: "${OCTOPUS_ADMIN_USERNAME}"
      ServerPassword: "${OCTOPUS_ADMIN_PASSWORD}"
      TargetEnvironment: "Development"
      TargetRole: "web-server"
      ServerUrl: "http://octopus-server:8080"
      ServerPort: "10943"
    stdin_open: true #Process sits and waits for ReadLine
    volumes:
      - "./docker/Volumes/polling-tentacle/Applications:C:/Applications"
      - "./docker/Volumes/polling-tentacle/TentacleHome:C:/TentacleHome"
    restart: always
